site:
  name: "Jae AHN • Portfolio"
  site: "https://ahn2001hanyang.github.io/astro-portfolio/"
  base: "/astro-portfolio/"       # GitHub Pages 仓库名
  trailingSlash: true             # 等价于 Astro 的 'always'，避免 404
  googleSiteVerificationId: ""

metadata:
  title:
    default: "Jae AHN — Software & AI Projects"
    template: "%s — Jae AHN"
  description: "个人博客与项目作品集：AI、游戏、Web 开发记录与复盘 · Personal blog & portfolio covering AI, games, and web development."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: "Jae AHN"
    images:
      # Step 15: 使用新的 OG 分享图（建议 1200×630）
      - url: "~/assets/images/og.png"
        width: 1200
        height: 630
    type: website
  twitter:
    handle: ""
    site: ""
    cardType: summary_large_image

# 默认语言：韩文；左右文方向为 LTR
i18n:
  language: ko
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: "/%slug%"
      robots:
        index: true
    list:
      isEnabled: true
      pathname: "blog"
      robots:
        index: true
    category:
      isEnabled: true
      pathname: "category"
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: "tag"
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: "system"
